### ISSUE TITLE
Removing the level indicator from a tile

### ISSUE THREAD

**Issue by hazymat** [OXRS-IO/OXRS-IO-WEBSITE#106]
During some of my testing of the level feature, I was looking for a way to remove a tile's level indicator. (Use case: you want it not to show the volume when radio is turned off.)

Despite the fact the tile level can only be set when the tile state is on, it doesn't automatically remove the level indicator when you turn the tile off.

My workaround is to send `"level: ""` however that is not documented; in fact the docs say that level must be a number not a string.

So - do we change the firmware to automatically remove the level indicator when tile state changes to off? Or should we document the fact that you can clear the level indicator by sending an empty string?

If the latter, what's the best way to show that in the docs (as a parameter can't have two types)?

**Comment by moinmoin-sh** [comment]
Not sure if I get you right, but for me the level indicator is turned off when the tile state is set to "off"

**Comment by moinmoin-sh** [comment]
@hazymat can we close this or is there still something that needs to be solved?

**Comment by hazymat** [comment]
Yes - please close this! Thanks
