### ISSUE TITLE
DIP switches for setting the MCP address are incorrect on the Modular Security and I2CRJ45 pages

### ISSUE THREAD

**Issue by sarreck** [OXRS-IO/OXRS-IO-WEBSITE#118]
0x23 and 0x24 are swapped around

**Comment by sumnerboy12** [comment]
@austinscreations I can't seem to assign this to you, but it is a pretty easy fix

**Comment by jonoxer** [comment]
0x23 is shown correctly, it's 0x24 onwards that are wrong. I'll see if I can fix it.
