### ISSUE TITLE
Document template links broken

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-WEBSITE#15]
Links on page https://oxrs.io/guides/writing-docs/templates/ to https://oxrs.io/guides/templates/hardware-template.html and https://oxrs.io/guides/templates/firmware-template.html are 404'ing.

**Comment by mrinc** [comment]
Interesting.

Should be changed to point to https://oxrs.io/templates/firmware-template.html /hardware respectively.

However https://oxrs.io/templates/firmware-template.html returns a blank page where the file legitimately is there

**Comment by mrinc** [comment]
Aha, githubpages aren't committed (probs 'templates' name is ignored)
