### ISSUE TITLE
add a page about Ethernet cabling

### ISSUE THREAD

**Issue by austinscreations** [OXRS-IO/OXRS-IO-WEBSITE#21]
recommendation to add a webpage about Ethernet cable colors and possible recommendation for what people may use for what.

Blue for LAN. 
Yellow for cctv
Green for poe devices.
Purple for access points 
White for non data devices.  Eg oxrs light switches
Orange
Red
black
grey

**There are standards for patch cords.**
Gray: Standard ethernet connection
Green: Crossover ethernet connection
Yellow: POE (power over ethernet)
Orange: Analog Non-Ethernet
Purple: Digital Non-Ethernet
Blue: Terminal server connection
Red: IP cameras
Black: additional general ethernet color for departmental use
Pink: additional general ethernet color for departmental use
White: additional general ethernet color for departmental use

**Comment by kghxkgh** [comment]
My biggest recommendation is to label your cables each end and sometimes in between where there might be several running next to each other.
