### ISSUE TITLE
Update config examples for new JSON Schema

### ISSUE THREAD

**Issue by sarreck** [OXRS-IO/OXRS-IO-WEBSITE#24]
The "Input Config" requires update to reflect the changes in the JSON Schema

{"inputs":[{"index": 4, "type": "contact"}]}

{"inputs":[{"index": 7, "type": "button", "invert": true}]}

**Comment by sarreck** [comment]
It would also be helpful to have an example showing how to configure more than one index number in the same JSON string

**Comment by sumnerboy12** [comment]
@sarreck I have updated the docs to show the new format - can you review and close this if you are happy with the changes?
