### ISSUE TITLE
"Guides" pages look broken

### ISSUE THREAD

**Issue by moinmoin-sh** [OXRS-IO/OXRS-IO-WEBSITE#44]
The pages under `Guides `look broken. No subsection headers are shown as links in the left hand navigation bar

**Comment by austinscreations** [comment]
that'd likely be my problem - i was working on those guide docs and still wasn't sure how i was going to lay things out. I've been busy doing other things and thus haven't written said docs yet.

**Comment by moinmoin-sh** [comment]
It was my impression, that something in the structure (layout render process ?) was broken and it can't be fixed by just writing .md files? I have no clue how the compiling of the pages works.

**Comment by austinscreations** [comment]
I'm betting it's going to be some possible editing to config.js and possibly the markdown on the webpages themselves.
i've added it to my big list of things to still update. I'm setup to both pull the latest webpage but also run it locally to test that things are the way they should be - hopefully i'll finish my backlog of projects and get some time to do more updates.

my current to do list: [https://docs.google.com/document/d/1p6uhm_Tehkd0sBhugXeKrqIOUXJgKwMPWctTnWPD8fI/edit?usp=sharing](https://docs.google.com/document/d/1p6uhm_Tehkd0sBhugXeKrqIOUXJgKwMPWctTnWPD8fI/edit?usp=sharing)
