### ISSUE TITLE
Style shows as buttonLevelDown. Should be buttonUpDown

### ISSUE THREAD

**Issue by kghxkgh** [OXRS-IO/OXRS-IO-WEBSITE#83]
In the table for the buttonUpDown CMND,
The style description is incorrect.
Style shows as buttonLevelDown. 
Should be buttonUpDown

https://oxrs.io/docs/firmware/touch-panel-esp32.html#json-parameters-10

![image](https://user-images.githubusercontent.com/74844260/232187728-aece4cc9-2345-4bc6-af8d-a935a9121ff4.png)

**Comment by hazymat** [comment]
buttonLevelDown is now deprecated in favour of buttonUpDownLevel

Suggest closing this issue and I will create a new issue to document the new version (buttonUpDownLevel)

**Comment by kghxkgh** [comment]
sure Mat.
