### ISSUE TITLE
Touchpanel, document tile style "buttonSelector"

### ISSUE THREAD

**Issue by moinmoin-sh** [OXRS-IO/OXRS-IO-WEBSITE#87]
example /cmnd payload
```JSON
{
  "tiles":[
    {
      "screen": 1,
      "tile": 2,
      "selectorList": ["off", "low", "medium", "full"],
      "selectorSelect": 1
    }
  ]
}
```

**Comment by hazymat** [comment]
Thanks for sharing the example /cmnd payload. Can you please also share an example conf/ payload (for base configuration)? Or can it be applied to any type of tile?

**Comment by moinmoin-sh** [comment]
You have to configure a tile with `style `set to `buttonSelector` first . Then the above `/cmnd` payload populates the selector
This  effects tiles of style `buttonSelector `only.

**Comment by hazymat** [comment]
This is done
