### ISSUE TITLE
TouchPanel, update image handling for background images (Release 2.4.4)

### ISSUE THREAD

**Issue by moinmoin-sh** [OXRS-IO/OXRS-IO-WEBSITE#99]
see PR  https://github.com/OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW/pull/66

**Comment by MakerDockio** [comment]
Once again bug thanks @moinmoin-sh . I have added the foundation docs showing the payloads for new funcitonality. [see here](https://oxrs.io/docs/firmware/touch-panel-esp32.html#add-a-tile-background-image) I have positioned this in the docs just below docs on adding a custom icon. Happy for any wordsmiths or Shakespeares to fluff it out.

I have also updated the Icon Generator and renamed it to the Asset Generator, this allows users to select either Icon or Background image to generate the associated payloads for ease.[see here](https://oxrs.io/tools/asset-generator.html). Ive searched out all references to the old Icon Generator and updated the links to prevent anyone hitting a 404.
